# Generated by Django 2.2 on 2021-10-01 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('set_verified', 'Выдавать разрешения на создавание новостей')]},
        ),
    ]
