# Generated by Django 2.2 on 2022-07-28 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='news_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_news.News', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_edit',
            field=models.DateField(auto_now=True, verbose_name='дата редактирования'),
        ),
    ]
