# Generated by Django 2.2 on 2022-08-10 09:15

import app_news.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_auto_20211027_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='fileblogpicture',
            options={'verbose_name': 'blog picture', 'verbose_name_plural': 'blog pictures'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': [('set_published', 'Mark news as published')], 'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=20, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_news.News', verbose_name='news'),
        ),
        migrations.AlterField(
            model_name='fileblogpicture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='fileblogpicture',
            name='file',
            field=models.FileField(upload_to=app_news.models.FileBlogPicture.user_directory_path, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='fileblogpicture',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='app_news.News', verbose_name='news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='news',
            name='fl_published',
            field=models.BooleanField(default=False, verbose_name='for home page'),
        ),
        migrations.AlterField(
            model_name='news',
            name='fl_ready_to_publish',
            field=models.BooleanField(verbose_name='publish to blog'),
        ),
        migrations.AlterField(
            model_name='news',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_at'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateField(db_index=True, default=None, null=True, verbose_name='published at'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_news.Tag', verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
